// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { HealthCheckGetResponse, LoginAccessTokenLoginAccessTokenPostData, LoginAccessTokenLoginAccessTokenPostResponse, HandlerGenerateGeneratePostResponse } from './types.gen';

export class DefaultService {
    /**
     * Health Check
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static healthCheckGet(): CancelablePromise<HealthCheckGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/'
        });
    }
    
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static accessTokenLoginAccessTokenPost(data: LoginAccessTokenLoginAccessTokenPostData): CancelablePromise<LoginAccessTokenLoginAccessTokenPostResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
}

export class RagService {
    /**
     * Handler Generate
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static handlerGenerateGeneratePost(): CancelablePromise<HandlerGenerateGeneratePostResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/generate'
        });
    }
    
}