// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_access_token_login_access_token_post = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type HealthCheckGetResponse = (unknown);

export type LoginAccessTokenLoginAccessTokenPostData = {
    formData: Body_login_access_token_login_access_token_post;
};

export type LoginAccessTokenLoginAccessTokenPostResponse = (Token);

export type HandlerGenerateGeneratePostResponse = (unknown);